/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.accountingagenda.view;

/**
 *
 * @author Alison Miranda, Bug Busters, DCCO-ESPE
 */
public class FrmEntryMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmEntryMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mniEntryAdministrator = new javax.swing.JMenuItem();
        mniEntryGuest = new javax.swing.JMenu();
        mniEntryGuest1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mniInformation = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniInstructions = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("\"MI AGENDA CONTABLE\"");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("\"MI AGENDA CONTABLE\"");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setText("BIENVENIDO");

        jMenu3.setText("Usuarios");

        jMenu4.setText("Administrador");

        mniEntryAdministrator.setText("Entrar");
        mniEntryAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEntryAdministratorActionPerformed(evt);
            }
        });
        jMenu4.add(mniEntryAdministrator);

        jMenu3.add(jMenu4);

        mniEntryGuest.setText("Invitado");

        mniEntryGuest1.setText("Entrar");
        mniEntryGuest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEntryGuest1ActionPerformed(evt);
            }
        });
        mniEntryGuest.add(mniEntryGuest1);

        jMenu3.add(mniEntryGuest);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Acerca de");

        mniInformation.setText("Información ");
        mniInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInformationActionPerformed(evt);
            }
        });
        jMenu1.add(mniInformation);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        mniInstructions.setText("Instrucciones");
        mniInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInstructionsActionPerformed(evt);
            }
        });
        jMenu2.add(mniInstructions);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniEntryAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEntryAdministratorActionPerformed
        FrmLogInAdministrator frmLogIn = new FrmLogInAdministrator();
        frmLogIn.setVisible(true);
        dispose();
    }//GEN-LAST:event_mniEntryAdministratorActionPerformed

    private void mniEntryGuest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEntryGuest1ActionPerformed
        FrmLogInGuest frmLogIn = new FrmLogInGuest();
        frmLogIn.setVisible(true);
        dispose();
    }//GEN-LAST:event_mniEntryGuest1ActionPerformed

    private void mniInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniInformationActionPerformed

    private void mniInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInstructionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniInstructionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEntryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEntryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEntryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEntryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEntryMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem mniEntryAdministrator;
    private javax.swing.JMenu mniEntryGuest;
    private javax.swing.JMenuItem mniEntryGuest1;
    private javax.swing.JMenuItem mniInformation;
    private javax.swing.JMenuItem mniInstructions;
    // End of variables declaration//GEN-END:variables
}
